### ISSUE TITLE
Add travis CI

### ISSUE THREAD

**Issue by helios175** [square/cycler#15]
Configure a simple travis build that runs:
1) compilation
2) unit tests
3) instrumentation test (for a soon to be sample app #16 ).

**Comment by zach-klippenstein** [comment]
I believe the default travis config runs `build connectedCheck`, which covers all those use cases.

**Comment by felipehjcosta** [comment]
Quick question: Why Travis CI instead of Actions?

**Comment by zach-klippenstein** [comment]
At the time this issue was filed, I believe we didn't have access to Actions. That might have changed by now. If available, actions should definitely be preferred over Travis.

**Comment by felipehjcosta** [comment]
Cool! Are you accepting PR?

**Comment by helios175** [comment]
Closing this as we now added the github builds.
More testing should eventually be added thou!
