### ISSUE TITLE
Upgrade Kotlin to 1.4

### ISSUE THREAD

**Issue by zach-klippenstein** [square/cycler#32]

**Comment by RudolfHladik** [comment]
Hi, I would like to take this as part of #Hacktoberfest if you don't mind.

**Comment by zach-klippenstein** [comment]
I think we might still need to depend on the Kotlin 1.3 stdlib even if we upgrade the compiler, at least for a few more weeks, for internal reasons. Or, since this library is mostly stable, we can probably just stay on an older version for now internally and hotfix from the last release if necessary. Up to @helios175.
